### ISSUE TITLE
[Project 1; Task 2] Output total number of pairs

### ISSUE THREAD

**Issue by jonahgeorge** [jordancrane/distributed-systems-coursework#3]
This is a really dumb requirement.... Going to have the make a chained reducer to count the number of records

**Comment by jordancrane** [comment]
Have you worked out the logistics of how to implement a chained reducer? I've been running into some issues trying to pass on the output of the first onto the second.

**Comment by jonahgeorge** [comment]
It appears that ChainReducers only allow you to add additional mappers to a reduce task (whatever that means). 

Not sure if you took a look already but I ended up just adding a second MapReduce job and adding the first job as a dependency of it. The only thing it does is map `<null, Text>` so it all gets sent to a single reducer and then counts the rows
